#' @title BgeeMetadata S4 class
#' 
#' @description An S4 class that contains all information to retrieve intergenic regions generated by Bgee.
#' 
#' @slot bgee_release Bgee release that will be used
#' @slot bgee_prefix String used to generate a bgee specific output directory
#' @slot fasta_intergenic_url URL to fasta file containing all intergenic regions as defined by the Bgee pipeline (https://github.com/BgeeDB/bgee_pipeline/tree/master/pipeline/RNA_Seq)
#' @slot ref_intergenic_ids_url URL to the file containing the list of true intergenic regions as defined by expertise of Bgee team (https://github.com/BgeeDB/bgee_pipeline/tree/master/pipeline/RNA_Seq)
#' @slot fasta_intergenic_name Name of the fasta file containing all intergenic regions that will be download to get_species_path()
#' @slot ref_intergenic_ids_name Name of the file containing the list of true  intergenic regions that will be download to get_species_path()
#'
BgeeMetadata <- setClass(
  # Set the name for the class
  Class = "BgeeMetadata",

  # Define the slots
  representation = representation(
    bgee_release = "character",
    bgee_prefix = "character",
    fasta_intergenic_url = "character",
    fasta_intergenic_name = "character",
    ref_intergenic_ids_name = "character"

  ),

  prototype = prototype(
    bgee_prefix = "BgeeCall_bgee",
    fasta_intergenic_name = "bgee_intergenic.fa.gz",
    ref_intergenic_ids_name = "bgee_ref_intergenic.tsv"
  )
)

setMethod(f = "initialize", signature ="BgeeMetadata" , definition = function(.Object, ...) {
  .Object <- callNextMethod()
  ## Get release information
  cat("\nQuerying Bgee to get release information...\n")
  allReleases <- try(.getBgeeRelease(removeFile = FALSE), silent=TRUE)
  if (class(allReleases) == "data.frame"){
    file.rename(from=file.path(getwd(), 'release.tsv'),
                to=file.path(getwd(), "release.tsv"))
  } else if (class(allReleases) == "try-error"){
    if (file.exists(file.path(getwd(), "release.tsv"))){
      cat(paste0("\nWARNING: BgeeCall could not access releases information from the internet, but a release information file was found in the download directory ",
                 getwd(), ". This release file will be used, but be warned that it may not be up to date!\n"))
      allReleases <- read.table(file.path(getwd(), "release.tsv"), header=TRUE, sep="\t")
    } else {
      stop("ERROR: BgeeCall could not access Bgee releases information. Is your internet connection working?")
    }
  }

  # if no release has been specified during instanciation take more recent release
  if (length(.Object@bgee_release) == 0) {
    .Object@bgee_release <- as.character(allReleases$release[1])
    .Object@fasta_intergenic_url <- as.character(allReleases$referenceIntergenicFastaURL[1])
  } else if (length(.Object@bgee_release) == 1) {
    if (.Object@bgee_release %in% allReleases$release) {
      .Object@bgee_release <- as.character(allReleases$release[allReleases$release == .Object@bgee_release])
      .Object@fasta_intergenic_url <- as.character(allReleases$referenceIntergenicFastaURL[allReleases$release == .Object@bgee_release])
    } else {
        stop("ERROR: The specified release number is invalid, or is not available for BgeeCall.")
    }
  } else {
    stop("ERROR: The specified release number is invalid.")
  }
  #validObject(object)
  .Object
})
